# Generated by Django 3.1.5 on 2021-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagepost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head1', models.CharField(default='', max_length=500)),
                ('chead1', models.CharField(default='', max_length=5000)),
                ('tags', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='app/images')),
            ],
        ),
    ]
